### ISSUE TITLE
Home Screen

### ISSUE THREAD

**Issue by IsaacCDHall** [joepritch/ReactTeamWeek#12]
## Use Case
Immediate introduction to game
## Description
Initial splash page, no tutorial needed. Menu will be upon first death

### This task is done when:
* This picture or better
  *  <img width="497" alt="Screen Shot 2019-05-13 at 3 37 09 PM" src="https://user-images.githubusercontent.com/45721766/57658966-7c730380-7595-11e9-8048-504c1e111566.png">

**Comment by ko1h** [comment]
finished welcome page.

**Comment by ko1h** [comment]
<img width="414" alt="Screen Shot 2019-05-14 at 11 38 44 AM" src="https://user-images.githubusercontent.com/16697271/57723542-b0a1ff00-763d-11e9-8534-8a9a744f1279.png">
